# Gitpod Configuration for AuraOS
image:
  file: Dockerfile.dev

# Ports to expose
ports:
  - port: 5173
    onOpen: open-browser
    name: AuraOS Frontend (Vite)

# Tasks to run on workspace start
tasks:
  - name: Setup and Start
    init: |
      echo "🚀 Setting up AuraOS development environment..."
      npm install
      echo "✅ Environment setup complete!"
    command: |
      echo "🎯 Starting AuraOS development server..."
      npm run dev
    openMode: split-right

# Environment variables
env:
  - name: NODE_ENV
    value: development

# VS Code extensions to install
vscode:
  extensions:
    - ms-vscode.vscode-typescript-next
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
    - redhat.vscode-yaml
    - ms-vscode.vscode-json
    - formulahendry.auto-rename-tag
    - christian-kohler.path-intellisense
    - ms-vscode.vscode-eslint
