version: '3.8'

services:
  # AuraOS Development Server (Vite + React)
  auraos-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auraos-server
    ports:
      - "5173:5173"  # Vite default port
    environment:
      - NODE_ENV=development
    volumes:
      - .:/workspace
      - /workspace/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  default:
    name: auraos-network