version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./gateway
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=development_jwt_secret
      - EXTERNAL_APP_API_KEY=dev_api_key_123
      - TELEGRAM_BOT_TOKEN=demo_telegram_token
      - AUTOPILOT_API_KEY=demo_autopilot_key
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./gateway:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  autopilot-service:
    build: ./autopilot-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTOPILOT_API_URL=http://localhost:3000
      - AUTOPILOT_API_KEY=demo_autopilot_key
    depends_on:
      redis:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    volumes:
      - ./autopilot-service:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build: ./telegram-bot
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TELEGRAM_BOT_TOKEN=demo_telegram_token
    depends_on:
      redis:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    volumes:
      - ./telegram-bot:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: