version: '3.8'

services:
  api-gateway:
    build: ./gateway
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=development_jwt_secret
      - EXTERNAL_APP_API_KEY=dev_api_key_123
    depends_on:
      - redis
    volumes:
      - ./gateway:/app
      - /app/node_modules
    command: npm run dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Autopilot Service (Placeholder)
  autopilot-service:
    image: node:18-alpine
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./autopilot:/app
    command: sh -c "echo 'Autopilot service placeholder' && sleep infinity"

  # Telegram Bot Service (Placeholder)
  telegram-bot:
    image: python:3.11-alpine
    ports:
      - "3003:3003"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./telegram_bot:/app
    command: sh -c "echo 'Telegram bot service placeholder' && sleep infinity"

volumes:
  redis_data: