# Prometheus configuration for AuraOS
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AuraOS Services
  - job_name: 'conversational-core'
    static_configs:
      - targets: ['conversational-core:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'file-organizer'
    static_configs:
      - targets: ['file-organizer:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'ide-agent'
    static_configs:
      - targets: ['ide-agent:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Redis metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # Nginx metrics (if nginx_exporter is available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 15s