openapi: 3.0.0
info:
  title: AuraOS A2A Gateway API
  description: API Gateway for Application-to-Application integration system
  version: 1.0.0
  contact:
    name: AuraOS Team
    email: support@auraos.com
servers:
  - url: http://localhost:3001
    description: Development server
  - url: https://api.auraos.com
    description: Production server

paths:
  /:
    get:
      summary: Gateway information
      description: Returns basic information about the A2A Gateway
      responses:
        '200':
          description: Gateway information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "AuraOS A2A Gateway"
                  version:
                    type: string
                    example: "1.0.0"
                  status:
                    type: string
                    example: "running"
                  timestamp:
                    type: string
                    format: date-time

  /api/auth/login:
    post:
      summary: User login
      description: Authenticate user and receive JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: "admin"
                password:
                  type: string
                  example: "admin123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      role:
                        type: string
                      permissions:
                        type: array
                        items:
                          type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid credentials"

  /api/messages/publish:
    post:
      summary: Publish message
      description: Publish a message to the message broker
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - source
                - type
                - payload
              properties:
                source:
                  type: string
                  example: "my-app"
                type:
                  type: string
                  example: "notification"
                payload:
                  type: object
                  example: {"message": "Hello World!"}
                correlation_id:
                  type: string
                  example: "req-123"
      responses:
        '200':
          description: Message published successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  eventId:
                    type: string
                  message:
                    type: string
                    example: "Event published successfully"
        '400':
          description: Missing required fields
        '401':
          description: Invalid API key

  /api/webhooks/incoming:
    post:
      summary: Generic webhook
      description: Handle incoming webhooks from external applications
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - source
                - type
              properties:
                source:
                  type: string
                  example: "external-app"
                type:
                  type: string
                  example: "webhook"
                payload:
                  type: object
                correlation_id:
                  type: string
      responses:
        '200':
          description: Webhook processed successfully
        '400':
          description: Missing required fields
        '401':
          description: Invalid API key

  /api/health:
    get:
      summary: Health check
      description: Check the health status of the gateway and its services
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                  services:
                    type: object
                    properties:
                      redis:
                        type: string
                        example: "healthy"
                      gateway:
                        type: string
                        example: "healthy"
                  uptime:
                    type: number
                    example: 3600
                  memory:
                    type: object
        '503':
          description: Service is unhealthy

  /api/metrics:
    get:
      summary: Prometheus metrics
      description: Expose Prometheus metrics for monitoring
      responses:
        '200':
          description: Metrics data
          content:
            text/plain:
              schema:
                type: string

securitySchemes:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
  BearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT

components:
  schemas:
    Event:
      type: object
      properties:
        event_id:
          type: string
        source:
          type: string
        type:
          type: string
        payload:
          type: object
        timestamp:
          type: string
          format: date-time
        correlation_id:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        role:
          type: string
        permissions:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time